//Section 1
Employees
| take 10

Employees
| count

Employees
| where role == "CTO"

Email
| where recipient == "alexis_khoza@solvisystems.com"
| count

Email
| where sender has "eskom.co.za"
| distinct sender
| count

OutboundNetworkEvents
| where src_ip == "10.10.0.7"
| distinct url
| count 

PassiveDns
| where domain contains "real"
| distinct domain 
| count 

PassiveDns
| where domain == "bit.ly"
| distinct ip

let mary_ips = 
Employees
| where name has "Mary"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in (mary_ips)
| distinct url
| count 

let mary_ips = Employees
| where name has "Mary"
| distinct username;
AuthenticationEvents
| where username in (mary_ips)
| count

//Section 2
//{
   description: "DETECTION RULE TRIGGERED",
   severity: "HIGH",
   rule_description: "SUSPICIOUS TEXT IN HTTP REQUEST",
   data: https://www.solvisystems.com/feedback?message=</script>. 
 <script>alert('xss')</script>
}

InboundNetworkEvents
| where url contains "alert"

let threat_actor_ips =
InboundNetworkEvents
| where user_agent contains "Opera/8.64"
| where timestamp between (datetime("2024-05-03") .. datetime("2024-05-05"))
| distinct src_ip;
InboundNetworkEvents
| where src_ip in (threat_actor_ips)
| where url contains "Pro"


let threat_actor_ips =
InboundNetworkEvents
| where user_agent contains "Opera/8.64"
| where timestamp between (datetime("2024-05-03") .. datetime("2024-05-05"))
| distinct src_ip;
let threat_actor_domain =
PassiveDns
| where ip  in (threat_actor_ips)
| distinct domain;
Email
| where link has_any (threat_actor_domain)
| extend file_name = tostring (parse_path(link).filename)
| distinct file_name

let threat_actor_ips =
InboundNetworkEvents
| where timestamp between (datetime("2024-05-03") .. datetime("2024-05-05"))
| where user_agent contains "Opera/8.64"
| distinct src_ip;
let threat_actor_domains = 
PassiveDns
| where ip in (threat_actor_ips)
| distinct domain;
let email_recipients = 
Email
| where link has_any (threat_actor_domains)
| extend email_recipient = parse_path(recipient).Filename
| distinct tostring(email_recipient);
Employees
| where email_addr in (email_recipients)
| distinct role

//
let threat_actor_ips =
InboundNetworkEvents
| where timestamp between (datetime("2024-05-03") .. datetime("2024-05-05"))
| where user_agent contains "Opera/8.64"
| distinct src_ip;
let threat_actor_domains = 
PassiveDns
| where ip in (threat_actor_ips)
| distinct domain;
Email
| where link has_any (threat_actor_domains)
//Did Carla click on the link in email? If so when? http://news-on-industry.com/search/online/files/public/Energy_Industry_Trends_2024_4_Solvi.docx

let carla_ip =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project ip_addr;
OutboundNetworkEvents
| where src_ip in (carla_ip)
| where url contains "Energy_Industry_Trends_2024_4_Solvi.docx"

//What file was observed on Carla's machine shortly after she executed the docx file?

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project username;
FileCreationEvents
| where username in (carla)
| where timestamp between (datetime(2024-05-01T15:58:29Z) .. datetime(2024-05-01T16:58:29Z))
| summarize count() by filename
// How many records do we have of this file being created on Solvi Systems computers?

FileCreationEvents
| where filename == "ecobug.exe"



//What IP address does ecobug.exe connect to in order to establish persistence?


let threat_actor_ips =
InboundNetworkEvents
| where user_agent contains "Opera/8.64"
| where timestamp between (datetime("2024-05-03") .. datetime("2024-05-05"))
| distinct src_ip;
let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project username;
ProcessEvents
| where username in (carla)
| where process_commandline has_any (threat_actor_ips)
| where process_name == "ecobug.exe" or process_commandline contains "ecobug.exe"

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project ip_addr;
NetworkFlow
| where src_ip in (carla)
| where dest_ip == "98.117.26.236"
| count

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project ip_addr;
NetworkFlow
| where src_ip in (carla)
| where dest_ip == "98.117.26.236"
| summarize connections_per_day = count() by bin(timestamp, 1d)

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project ip_addr;
NetworkFlow
| where src_ip in (carla)
| where dest_ip == "98.117.26.236"
| extend time_only = format_datetime(timestamp, "HH:mm:ss")
| project timestamp, time_only
| order by timestamp asc

NetworkFlow
| where dest_ip == "98.117.26.236"
| count

let solvi_ips =
Employees
| project ip_addr;
NetworkFlow
| where src_ip in (solvi_ips)
| where dest_ip == "98.117.26.236"
| distinct src_ip

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project username;
ProcessEvents
| where username in (carla)
| where timestamp between (datetime(2024-05-02) .. datetime(2024-05-03))
| where process_commandline contains "net user" or process_commandline contains "useradd"
| project timestamp, process_name, process_commandline
| order by timestamp asc

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project username;
ProcessEvents
| where username in (carla)
| where timestamp > datetime(2024-05-01T15:58:29Z)
| where process_commandline has_any (
    "whoami", "ipconfig", "netstat", "net user", "net group",
    "systeminfo", "tasklist", "net localgroup", "query user",
    "nltest", "ping", "tracert", "arp", "route", "hostname",
    "net view", "wmic", "dir", "tree", "net share"
  )
| project timestamp, process_name, process_commandline
| order by timestamp desc
| take 1

let carla =
Employees
| where email_addr == 'carla_wharton@solvisystems.com'
| project username;
ProcessEvents
| where username in (carla)
| project timestamp, process_name, process_commandline
| order by timestamp asc

ProcessEvents
| where process_commandline contains "net use"
| summarize distinct_commands = dcount(process_commandline) by username
| order by distinct_commands desc

ProcessEvents
| where username == "cawharton"
| where process_commandline contains "net use"
| distinct process_commandline

//check if they added this user to administrators:

ProcessEvents
| where username == "cawharton"
| where process_commandline contains "gu@rd!an"
| project timestamp, process_commandline
| order by timestamp asc

// all user not only carla

ProcessEvents
| where process_commandline contains "net use"
| project timestamp, process_commandline
| order by timestamp asc

//How many distinct hosts was this command run on?


ProcessEvents
| where process_commandline contains "net use /PERSISTENT:YES"
| project timestamp, hostname, username, process_commandline
| order by timestamp asc

//What is the timestamp for the first time this command was run?

ProcessEvents
| where process_commandline contains "net use /PERSISTENT:YES"
| project timestamp, hostname, username, process_commandline
| order by timestamp asc
| take 1

Employees
//| where username == "alpetrov"
//| where username == "jalee"
| where username == "tagreen"

//What is the command used to copy files related to SoftwareDevelopment?

ProcessEvents
| where username == "alpetrov"
| where process_commandline contains "SoftwareDevelopment"
| project timestamp, process_commandline
| order by timestamp asc

ProcessEvents
| where username == "alpetrov"
| where process_commandline contains "SoftwareDevelopment"
      or process_commandline has_any (".zip", ".rar", ".7z", ".tar")
| project timestamp, process_commandline
| order by timestamp asc

//The next day the data was exfiltrated using what command? " curl"
ProcessEvents
| where username == "alpetrov"
| where process_commandline contains "SoftwareDevelopment"
      or process_commandline has_any (".zip", ".rar", ".7z", ".tar")
| project timestamp, process_commandline
| order by timestamp asc

//How many accounts were used by the threat actor to exfiltrate sensitive information from Solvi Systems?

ProcessEvents
| where process_commandline contains "curl -F 'file="
| project timestamp, hostname, username, process_commandline
| order by timestamp asc

//The threat actors were observed reading an "internal process" document from an internal portal called ____.solvisystems.com


InboundNetworkEvents
| where url contains ".solvisystems.com"
| where url has_any ("process", "internal", "document", "portal")
| project timestamp, url
| order by timestamp asc

//What was the subject of those emails?

// 1. Have email adress
Employees
| where username in ("alpetrov", "jalee", "tagreen")


Email
| where sender in ("alexei_petrov@solvisystems.com", "jamie_lee@solvisystems.com", "taylor_green@solvisystems.com")
| where subject contains "software"
| project timestamp, sender, recipient, subject
| order by timestamp asc
